all: myshell
myshell: shell.h shell.c run_command.c redirect_out.c redirect_in.c pipe_present.c pipe_command.c parse.c is_background.c builtin.c
	gcc shell.h shell.c run_command.c redirect_out.c redirect_in.c pipe_present.c pipe_command.c parse.c is_background.c builtin.c -o myshell