all: hostinfo mydate printdir mycat pipe_ls
hostinfo: hostinfo.c
	gcc hostinfo.c -o hostinfo
mydate: mydate.c
	gcc mydate.c -o mydate
printdir: printdir.c
	gcc printdir.c -o printdir
mycat: mycat.c
	gcc mycat.c -o mycat
pipe_ls: pipe_ls.c
	gcc pipe_ls.c -o pipe_ls
